# header_map.py
from stable import (
    get_stat_value, get_title, get_asin, sales_rank_current, used_current,
    sales_rank_30_days_avg, sales_rank_90_days_avg, sales_rank_180_days_avg,
    sales_rank_365_days_avg, package_quantity, package_weight, package_height,
    package_length, package_width, used_like_new, used_very_good, used_good,
    used_acceptable, new_3rd_party_fbm_current, list_price
)
from Keepa_Deals import (
    new_3rd_party_fbm, used_like_new as deals_used_like_new,
    used_very_good as deals_used_very_good, used_good as deals_used_good,
    used_acceptable as deals_used_acceptable, used_offer_count_current
)

FUNCTION_MAP = {
    "Percent Down 90": None,
    "Avg. Price 90": None,
    "Percent Down 365": None,
    "Avg. Price 365": None,
    "Price Now": None,
    "Price Now Source": None,
    "Deal found": None,
    "AMZ link": None,
    "Keepa Link": None,
    "Title": get_title,
    "last update": None,
    "last price change": None,
    "Sales Rank - Reference": None,
    "Reviews - Rating": None,
    "Reviews - Review Count": None,
    "FBA Pick&Pack Fee": None,
    "Referral Fee %": None,
    "Tracking since": None,
    "Categories - Root": None,
    "Categories - Sub": None,
    "Categories - Tree": None,
    "ASIN": get_asin,
    "Freq. Bought Together": None,
    "Type": None,
    "Manufacturer": None,
    "Brand": None,
    "Product Group": None,
    "Variation Attributes": None,
    "Item Type": None,
    "Author": None,
    "Contributors": None,
    "Binding": None,
    "Number of Items": None,
    "Number of Pages": None,
    "Publication Date": None,
    "Languages": None,
    "Package - Quantity": package_quantity,
    "Package Weight": package_weight,
    "Package Height": package_height,
    "Package Length": package_length,
    "Package Width": package_width,
    "Listed since": None,
    "Edition": None,
    "Release Date": None,
    "Format": None,
    "Sales Rank - Current": sales_rank_current,
    "Sales Rank - 30 days avg.": sales_rank_30_days_avg,
    "Sales Rank - 60 days avg.": None,
    "Sales Rank - 90 days avg.": sales_rank_90_days_avg,
    "Sales Rank - 180 days avg.": sales_rank_180_days_avg,
    "Sales Rank - 365 days avg.": sales_rank_365_days_avg,
    "Sales Rank - Lowest": None,
    "Sales Rank - Lowest 365 days": None,
    "Sales Rank - Highest": None,
    "Sales Rank - Highest 365 days": None,
    "Sales Rank - Drops last 30 days": None,
    "Sales Rank - Drops last 60 days": None,
    "Sales Rank - Drops last 90 days": None,
    "Sales Rank - Drops last 180 days": None,
    "Sales Rank - Drops last 365 days": None,
    "Buy Box - Current": None,
    "Buy Box - 30 days avg.": None,
    "Buy Box - 60 days avg.": None,
    "Buy Box - 90 days avg.": None,
    "Buy Box - 180 days avg.": None,
    "Buy Box - 365 days avg.": None,
    "Buy Box - Lowest": None,
    "Buy Box - Lowest 365 days": None,
    "Buy Box - Highest": None,
    "Buy Box - Highest 365 days": None,
    "Buy Box - 90 days OOS": None,
    "Buy Box - Stock": None,
    "Amazon - Current": None,
    "Amazon - 30 days avg.": None,
    "Amazon - 60 days avg.": None,
    "Amazon - 90 days avg.": None,
    "Amazon - 180 days avg.": None,
    "Amazon - 365 days avg.": None,
    "Amazon - Lowest": None,
    "Amazon - Lowest 365 days": None,
    "Amazon - Highest": None,
    "Amazon - Highest 365 days": None,
    "Amazon - 90 days OOS": None,
    "Amazon - Stock": None,
    "New - Current": None,
    "New - 30 days avg.": None,
    "New - 60 days avg.": None,
    "New - 90 days avg.": None,
    "New - 180 days avg.": None,
    "New - 365 days avg.": None,
    "New - Lowest": None,
    "New - Lowest 365 days": None,
    "New - Highest": None,
    "New - Highest 365 days": None,
    "New - 90 days OOS": None,
    "New - Stock": None,
    "New, 3rd Party FBA - Current": None,
    "New, 3rd Party FBA - 30 days avg.": None,
    "New, 3rd Party FBA - 60 days avg.": None,
    "New, 3rd Party FBA - 90 days avg.": None,
    "New, 3rd Party FBA - 180 days avg.": None,
    "New, 3rd Party FBA - 365 days avg.": None,
    "New, 3rd Party FBA - Lowest": None,
    "New, 3rd Party FBA - Lowest 365 days": None,
    "New, 3rd Party FBA - Highest": None,
    "New, 3rd Party FBA - Highest 365 days": None,
    "New, 3rd Party FBA - 90 days OOS": None,
    "New, 3rd Party FBA - Stock": None,
    "New, 3rd Party FBM - Current": new_3rd_party_fbm_current,
    "New, 3rd Party FBM - 30 days avg.": new_3rd_party_fbm,
    "New, 3rd Party FBM - 60 days avg.": new_3rd_party_fbm,
    "New, 3rd Party FBM - 90 days avg.": new_3rd_party_fbm,
    "New, 3rd Party FBM - 180 days avg.": new_3rd_party_fbm,
    "New, 3rd Party FBM - 365 days avg.": new_3rd_party_fbm,
    "New, 3rd Party FBM - Lowest": None,
    "New, 3rd Party FBM - Lowest 365 days": None,
    "New, 3rd Party FBM - Highest": None,
    "New, 3rd Party FBM - Highest 365 days": None,
    "New, 3rd Party FBM - 90 days OOS": None,
    "New, 3rd Party FBM - Stock": new_3rd_party_fbm,
    "Buy Box Used - Current": None,
    "Buy Box Used - 30 days avg.": None,
    "Buy Box Used - 60 days avg.": None,
    "Buy Box Used - 90 days avg.": None,
    "Buy Box Used - 180 days avg.": None,
    "Buy Box Used - 365 days avg.": None,
    "Buy Box Used - Lowest": None,
    "Buy Box Used - Lowest 365 days": None,
    "Buy Box Used - Highest": None,
    "Buy Box Used - Highest 365 days": None,
    "Buy Box Used - 90 days OOS": None,
    "Buy Box Used - Stock": None,
    "Used - Current": used_current,
    "Used - 30 days avg.": None,
    "Used - 60 days avg.": None,
    "Used - 90 days avg.": None,
    "Used - 180 days avg.": None,
    "Used - 365 days avg.": None,
    "Used - Lowest": None,
    "Used - Lowest 365 days": None,
    "Used - Highest": None,
    "Used - Highest 365 days": None,
    "Used - 90 days OOS": None,
    "Used - Stock": None,
    "Used, like new - Current": used_like_new,
    "Used, like new - 30 days avg.": deals_used_like_new,
    "Used, like new - 60 days avg.": deals_used_like_new,
    "Used, like new - 90 days avg.": deals_used_like_new,
    "Used, like new - 180 days avg.": deals_used_like_new,
    "Used, like new - 365 days avg.": deals_used_like_new,
    "Used, like new - Lowest": None,
    "Used, like new - Lowest 365 days": None,
    "Used, like new - Highest": None,
    "Used, like new - Highest 365 days": None,
    "Used, like new - 90 days OOS": deals_used_like_new,
    "Used, like new - Stock": deals_used_like_new,
    "Used, very good - Current": used_very_good,
    "Used, very good - 30 days avg.": deals_used_very_good,
    "Used, very good - 60 days avg.": deals_used_very_good,
    "Used, very good - 90 days avg.": deals_used_very_good,
    "Used, very good - 180 days avg.": deals_used_very_good,
    "Used, very good - 365 days avg.": deals_used_very_good,
    "Used, very good - Lowest": None,
    "Used, very good - Lowest 365 days": None,
    "Used, very good - Highest": None,
    "Used, very good - Highest 365 days": None,
    "Used, very good - 90 days OOS": None,
    "Used, very good - Stock": deals_used_very_good,
    "Used, good - Current": used_good,
    "Used, good - 30 days avg.": deals_used_good,
    "Used, good - 60 days avg.": deals_used_good,
    "Used, good - 90 days avg.": deals_used_good,
    "Used, good - 180 days avg.": deals_used_good,
    "Used, good - 365 days avg.": deals_used_good,
    "Used, good - Lowest": None,
    "Used, good - Lowest 365 days": None,
    "Used, good - Highest": None,
    "Used, good - Highest 365 days": None,
    "Used, good - 90 days OOS": deals_used_good,
    "Used, good - Stock": deals_used_good,
    "Used, acceptable - Current": used_acceptable,
    "Used, acceptable - 30 days avg.": deals_used_acceptable,
    "Used, acceptable - 60 days avg.": deals_used_acceptable,
    "Used, acceptable - 90 days avg.": deals_used_acceptable,
    "Used, acceptable - 180 days avg.": deals_used_acceptable,
    "Used, acceptable - 365 days avg.": deals_used_acceptable,
    "Used, acceptable - Lowest": None,
    "Used, acceptable - Lowest 365 days": None,
    "Used, acceptable - Highest": None,
    "Used, acceptable - Highest 365 days": None,
    "Used, acceptable - 90 days OOS": deals_used_acceptable,
    "Used, acceptable - Stock": deals_used_acceptable,
    "List Price - Current": list_price,
    "List Price - 30 days avg.": None,
    "List Price - 60 days avg.": None,
    "List Price - 90 days avg.": None,
    "List Price - 180 days avg.": None,
    "List Price - 365 days avg.": None,
    "List Price - Lowest": None,
    "List Price - Lowest 365 days": None,
    "List Price - Highest": None,
    "List Price - Highest 365 days": None,
    "List Price - 90 days OOS": None,
    "List Price - Stock": None,
    "New Offer Count - Current": None,
    "New Offer Count - 30 days avg.": None,
    "New Offer Count - 60 days avg.": None,
    "New Offer Count - 90 days avg.": None,
    "New Offer Count - 180 days avg.": None,
    "New Offer Count - 365 days avg.": None,
    "Used Offer Count - Current": used_offer_count_current,
    "Used Offer Count - 30 days avg.": None,
    "Used Offer Count - 60 days avg.": None,
    "Used Offer Count - 90 days avg.": None,
    "Used Offer Count - 180 days avg.": None,
    "Used Offer Count - 365 days avg.": None
}